# -*- coding: utf-8 -*-
"""
Created on Mon May 13 11:51:47 2024

@author: eloua
"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
# from ... import Ui_MainWindow
from PyQt5.QtWidgets import QMainWindow, QApplication
import combat as cb
from combat import *
import deplacement_joueur as dj
from deplacement_joueur import *





class Ui_MainWindow(object):
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boutonTest = QtWidgets.QPushButton(self.centralwidget)
        self.boutonTest.setGeometry(QtCore.QRect(90, 70, 141, 61))
        self.boutonTest.setObjectName("boutonTest")
        
        self.boutonTest.clicked.connect(self.fonctionBoutonTest)
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 180, 141, 91))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boutonTest.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        
        
    def fonctionBoutonTest(self):
        pikachu = pk.Pokemon(pk.df_n[24,:], (5,5))
        rattata = pk.Pokemon(pk.df_n[18,:], (5,5))
        bulbasaur = pk.Pokemon(pk.df_n[0,:], (5,5))
        liste_pok_j1 = [pikachu, rattata, bulbasaur]
        J1 = dj.Joueur('j1', liste_pok_j1, 45)
        
        combat2 = cb.Combat(J1, bulbasaur, rattata)
        print("PV de", combat2.pok_def.name, "avant l'attaque simple de", combat2.pok_att.name, "de valeur", combat2.pok_att.attack-combat2.pok_def.defense, ":", combat2.pok_def.hp_restant)
        combat2.attaque()
        print("PV de", combat2.pok_def.name, "après l'attaque simple de", combat2.pok_att.name, ":", combat2.pok_def.hp_restant)

        print("\n***\nPV de", combat2.pok_def.name, "avant l'attaque spéciale de", combat2.pok_att.name, ":", combat2.pok_def.hp_restant)
        combat2.attaque()
        print("PV de", combat2.pok_def.name, "après l'attaque spéciale de", combat2.pok_att.name, ":", combat2.pok_def.hp_restant)   
    


class XXXXWindow (QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(XXXXWindow, self).__init__(parent)
        self.setupUi(self)
        # ...

if __name__ == "__main__":
    def run_app():
        app = QApplication(sys.argv)
        mainWin = XXXXWindow()
        mainWin.show()
        app.exec_()
    
    choix = input("Entrez <oui> si vous voulez ouvrir la fenetre, <non> sinon :")
    if choix == "oui":
        run_app()
    elif choix == "non":
        print("raté")